<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="OfficeManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VIJAY;Initial Catalog=TestDB;Integrated Security=True" SettingsObjectName="DataLib.Properties.Settings" SettingsPropertyName="TestDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AcademicYear" Member="AcademicYears">
    <Type Name="AcademicYear">
      <Column Name="AcademicYearId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AcademicYearStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AcademicYearEnd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AcademicYear_Account" Member="Accounts" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="Account" />
      <Association Name="AcademicYear_FeeMaster" Member="FeeMasters" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="FeeMaster" />
      <Association Name="AcademicYear_ScholarShipDetail" Member="ScholarShipDetails" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="ScholarShipDetail" />
      <Association Name="AcademicYear_TransactionDetail" Member="TransactionDetails" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="TransactionDetail" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PasswordChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserTitle" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_TransactionDetail" Member="TransactionDetails" ThisKey="UserId" OtherKey="UserId" Type="TransactionDetail" />
      <Association Name="User_UserGroupAssociation" Member="UserGroupAssociations" ThisKey="UserId" OtherKey="UserId" Type="UserGroupAssociation" />
      <Association Name="Address_User" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CarryFarwordFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeePaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AcademicYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MediumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_TransactionDetail" Member="TransactionDetails" ThisKey="AccountId" OtherKey="AccountId" Type="TransactionDetail" />
      <Association Name="AcademicYear_Account" Member="AcademicYear" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="AcademicYear" IsForeignKey="true" />
      <Association Name="Class_Account" Member="Class" ThisKey="ClassId" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
      <Association Name="Medium_Account" Member="Medium" ThisKey="MediumId" OtherKey="MediumId" Type="Medium" IsForeignKey="true" />
      <Association Name="Student_Account" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdrressLineOne" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Village" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Address_User" Member="Users" ThisKey="AddressId" OtherKey="AddressId" Type="User" />
      <Association Name="Address_Student" Member="Students" ThisKey="AddressId" OtherKey="AddressId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Cast" Member="Casts">
    <Type Name="Cast">
      <Column Name="CastId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Cast_Student" Member="Students" ThisKey="CastId" OtherKey="CastId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Class_Account" Member="Accounts" ThisKey="ClassId" OtherKey="ClassId" Type="Account" />
      <Association Name="Class_FeeMaster" Member="FeeMasters" ThisKey="ClassId" OtherKey="ClassId" Type="FeeMaster" />
      <Association Name="Class_Student" Member="Students" ThisKey="ClassId" OtherKey="Class" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.ExamSubjectMarks" Member="ExamSubjectMarks">
    <Type Name="ExamSubjectMark">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarksObtained" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExamType" Member="ExamTypes">
    <Type Name="ExamType">
      <Column Name="ExamTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerSubjectMarks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PassingMarksPerSubject" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FeeMaster" Member="FeeMasters">
    <Type Name="FeeMaster">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MediumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AcademicYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AcademicYear_FeeMaster" Member="AcademicYear" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="AcademicYear" IsForeignKey="true" />
      <Association Name="Class_FeeMaster" Member="Class" ThisKey="ClassId" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
      <Association Name="Medium_FeeMaster" Member="Medium" ThisKey="MediumId" OtherKey="MediumId" Type="Medium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Group_UserGroupAssociation" Member="UserGroupAssociations" ThisKey="GroupId" OtherKey="GroupId" Type="UserGroupAssociation" />
    </Type>
  </Table>
  <Table Name="dbo.Medium" Member="Mediums">
    <Type Name="Medium">
      <Column Name="MediumId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MediumName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Medium_Account" Member="Accounts" ThisKey="MediumId" OtherKey="MediumId" Type="Account" />
      <Association Name="Medium_FeeMaster" Member="FeeMasters" ThisKey="MediumId" OtherKey="MediumId" Type="FeeMaster" />
      <Association Name="Medium_Student" Member="Students" ThisKey="MediumId" OtherKey="MediumId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.ScholarShip" Member="ScholarShips">
    <Type Name="ScholarShip">
      <Column Name="ScholarShipId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScholarShipName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ScholarShip_ScholarShipDetail" Member="ScholarShipDetails" ThisKey="ScholarShipId" OtherKey="ScholarShipTypeId" Type="ScholarShipDetail" />
    </Type>
  </Table>
  <Table Name="dbo.ScholarShipDetails" Member="ScholarShipDetails">
    <Type Name="ScholarShipDetail">
      <Column Name="ScholarShipDetailsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScholarShipTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountSanctioned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateSanctioned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AcademicYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AcademicYear_ScholarShipDetail" Member="AcademicYear" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="AcademicYear" IsForeignKey="true" />
      <Association Name="ScholarShip_ScholarShipDetail" Member="ScholarShip" ThisKey="ScholarShipTypeId" OtherKey="ScholarShipId" Type="ScholarShip" IsForeignKey="true" />
      <Association Name="Student_ScholarShipDetail" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Section_Student" Member="Students" ThisKey="SectionId" OtherKey="SectionId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CastId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MotherName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MediumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Student_Account" Member="Accounts" ThisKey="StudentId" OtherKey="StudentId" Type="Account" />
      <Association Name="Student_ScholarShipDetail" Member="ScholarShipDetails" ThisKey="StudentId" OtherKey="StudentId" Type="ScholarShipDetail" />
      <Association Name="Student_TransactionDetail" Member="TransactionDetails" ThisKey="StudentId" OtherKey="StudentId" Type="TransactionDetail" />
      <Association Name="Address_Student" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
      <Association Name="Cast_Student" Member="Cast" ThisKey="CastId" OtherKey="CastId" Type="Cast" IsForeignKey="true" />
      <Association Name="Class_Student" Member="Class1" ThisKey="Class" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
      <Association Name="Medium_Student" Member="Medium" ThisKey="MediumId" OtherKey="MediumId" Type="Medium" IsForeignKey="true" />
      <Association Name="Section_Student" Member="Section" ThisKey="SectionId" OtherKey="SectionId" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubjectMaster" Member="SubjectMasters">
    <Type Name="SubjectMaster">
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SubjectTable" Member="SubjectTables">
    <Type Name="SubjectTable">
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MediumId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionDetails" Member="TransactionDetails">
    <Type Name="TransactionDetail">
      <Column Name="TransactionDetailsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountPaid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePaid" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AcademicYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rejected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="AcademicYear_TransactionDetail" Member="AcademicYear" ThisKey="AcademicYearId" OtherKey="AcademicYearId" Type="AcademicYear" IsForeignKey="true" />
      <Association Name="Account_TransactionDetail" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
      <Association Name="Student_TransactionDetail" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
      <Association Name="User_TransactionDetail" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.trig" Member="trigs">
    <Type Name="trig">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.trig_archive" Member="trig_archives">
    <Type Name="trig_archive">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroupAssociation" Member="UserGroupAssociations">
    <Type Name="UserGroupAssociation">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserGroupAssociation_UserGroupAssociation" Member="UserGroupAssociation2" ThisKey="UserId,GroupId" OtherKey="UserId,GroupId" Type="UserGroupAssociation" Cardinality="One" />
      <Association Name="Group_UserGroupAssociation" Member="Group" ThisKey="GroupId" OtherKey="GroupId" Type="Group" IsForeignKey="true" />
      <Association Name="User_UserGroupAssociation" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="UserGroupAssociation_UserGroupAssociation" Member="UserGroupAssociation1" ThisKey="UserId,GroupId" OtherKey="UserId,GroupId" Type="UserGroupAssociation" IsForeignKey="true" />
    </Type>
  </Table>
</Database>